version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: customuser
      POSTGRES_PASSWORD: custompassword
      POSTGRES_DB: customdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:





